### PR TITLE
Fix issue #20

### LINKED ISSUE #20: Entering a ISBN of -1 causes a javascript error
**Steps to reproduce**

1. Go to http://alphabooks-step-2020.appspot.com/
2. Log in
3. Enter "-1" into the ISBN search field
4. Click "Search!"

**Expected behavior**
I am told that -1 is an invalid ISBN.

**Actual behavior**
Nothing happens to the page and there is a javascript error:

```javascript
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at addBooksGrid (bookScript.js:92)
    at bookScript.js:20
```

### PR DESCRIPTION
**Pull request by anamariamilcu**
Added a function that explicitly checks if Google Books API actually offers a response with a list of books and also a unit test for it.

### CODE REVIEW

**Review by ak47na — APPROVED** [review]

File: src/main/webapp/bookScript.js [hunk 1]
```diff
@@ -17,7 +17,9 @@ document.addEventListener('DOMContentLoaded', () => {
           fetch(URL).then(response => {
             if (response.status === 200) {
               response.json().then(result => {
-                addBooksGrid(result.items);
+                if (extractBookList(result) !== null) {
+                  addBooksGrid(extractBookList(result));
+                }
```
Comment (ghost) [inline src/main/webapp/bookScript.js]: No need to call this twice :)

```suggestion
                const bookList = extractBookList(result);
                if (bookList !== null) {
                  addBooksGrid(bookList);
                }
```

**Review by ghost — APPROVED** [review]

File: src/main/webapp/bookScript.js (hunk 1 above)
Comment (anamariamilcu) [reply src/main/webapp/bookScript.js]: Fixed it
